### PR TITLE
Turn into a project people can build

### PR DESCRIPTION
**Pull request by bitemyapp**

### CODE REVIEW

**Comment by ddssff** [comment]
I was planning to replace the String type used for variables and functions into two distinct type classes, so we could see what happens if we used enumerated types or Ints for those.

**Comment by bitemyapp** [comment]
@ddssff I realize people brought up the String values in the thread, but I doubt that's most of your performance problem and the Reddit post you made implied you were principally concerned with the slowness.

The Strings will use extra heap but your main problem is the algorithm's underlying asymptotics. Recursively concatenating `[]` is not a recipe for happy-making.

**Comment by ddssff** [comment]
It is absolutely true I am only concerned with the slowness.

**Comment by ddssff** [comment]
I will merge this now.

**Comment by ddssff** [comment]
But please continue!

**Comment by bitemyapp** [comment]
@ddssff then I'd recommend focusing on the biggest performance problem. There are roughly three ways you can go:
1. Rewrite the code to avoid using (++) in a loop.
2. dlist
3. Data.Sequence

I haven't benchmarked or profiled it, but the code in the project is doing something common to slow code in Haskell.

http://stackoverflow.com/questions/5188286/idiomatic-efficient-haskell-append

https://wiki.haskell.org/Performance#Data.Sequence_vs._lists

https://wiki.haskell.org/How_to_work_on_lists

I've added it to my repo, but you'll want to enable optimization (`-O` or `-O2`) as well.

**Pull request merged**
